import { ChessBoard } from '@models/index';

export const chessBoardDefault: ChessBoard = [
  [
    { piece: 'Rook', faction: 'white' },
    { piece: 'Knight', faction: 'white' },
    { piece: 'Bishop', faction: 'white' },
    { piece: 'King', faction: 'white' },
    { piece: 'Queen', faction: 'white' },
    { piece: 'Bishop', faction: 'white' },
    { piece: 'Knight', faction: 'white' },
    { piece: 'Rook', faction: 'white' },
  ],
  [
    { piece: 'Pawn', faction: 'white' },
    { piece: 'Pawn', faction: 'white' },
    { piece: 'Pawn', faction: 'white' },
    { piece: 'Pawn', faction: 'white' },
    { piece: 'Pawn', faction: 'white' },
    { piece: 'Pawn', faction: 'white' },
    { piece: 'Pawn', faction: 'white' },
    { piece: 'Pawn', faction: 'white' },
  ],
  [
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
  ],
  [
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
  ],
  [
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
  ],
  [
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    // { piece: 'Bishop', faction: 'white' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
  ],
  [
    { piece: 'Pawn', faction: 'black' },
    { piece: 'Pawn', faction: 'black' },
    { piece: 'Pawn', faction: 'black' },
    { piece: 'Pawn', faction: 'black' },
    { piece: 'Pawn', faction: 'black' },
    { piece: 'Pawn', faction: 'black' },
    { piece: 'Pawn', faction: 'black' },
    { piece: 'Pawn', faction: 'black' },
  ],
  [
    { piece: 'Rook', faction: 'black' },
    { piece: 'Knight', faction: 'black' },
    { piece: 'Bishop', faction: 'black' },
    { piece: 'King', faction: 'black' },
    { piece: 'Queen', faction: 'black' },
    { piece: 'Bishop', faction: 'black' },
    { piece: 'Knight', faction: 'black' },
    { piece: 'Rook', faction: 'black' },
  ],
];

export const chessBoardTesting: ChessBoard = [
  [
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
  ],
  [
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
  ],
  [
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
  ],
  [
    { piece: 'empty', faction: 'neutral' },
    { piece: 'Bishop', faction: 'white' },
    { piece: 'Rook', faction: 'white' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
  ],
  [
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
  ],
  [
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'Bishop', faction: 'white' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'Queen', faction: 'black' },
    { piece: 'empty', faction: 'neutral' },
  ],
  [
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
  ],
  [
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
    { piece: 'empty', faction: 'neutral' },
  ],
];
